CREATE TABLE IF NOT EXISTS users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(120) NOT NULL,
 email VARCHAR(180) NOT NULL UNIQUE,
 password_hash VARCHAR(100) NOT NULL,
 role VARCHAR(20) NOT NULL CHECK (role IN ('BUYER','SELLER','ADMIN')),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS products (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 seller_id BIGINT NOT NULL,
 name VARCHAR(180) NOT NULL,
 description VARCHAR(2000) NOT NULL,
 price DECIMAL(10,2) NOT NULL CHECK (price >= 0),
 stock_qty INT NOT NULL CHECK (stock_qty >= 0),
 category VARCHAR(80) NOT NULL,
 image_url VARCHAR(1000),
 listing_type VARCHAR(10) NOT NULL DEFAULT 'SALE' CHECK (listing_type IN ('SALE','RENT')),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 CONSTRAINT fk_product_seller FOREIGN KEY (seller_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_products_seller ON products(seller_id);
CREATE TABLE IF NOT EXISTS orders (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 buyer_id BIGINT NOT NULL,
 status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING','CONFIRMED','SHIPPED','DELIVERED','CANCELLED')),
 total_amount DECIMAL(10,2) NOT NULL,
 shipping_name VARCHAR(120) NOT NULL DEFAULT '',
 shipping_address VARCHAR(500) NOT NULL DEFAULT '',
 shipping_phone VARCHAR(20) NOT NULL DEFAULT '',
 payment_method VARCHAR(10) NOT NULL DEFAULT 'COD',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 CONSTRAINT fk_order_buyer FOREIGN KEY (buyer_id) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_orders_buyer ON orders(buyer_id);
CREATE TABLE IF NOT EXISTS order_items (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 order_id BIGINT NOT NULL,
 product_id BIGINT NOT NULL,
 quantity INT NOT NULL CHECK (quantity > 0),
 unit_price DECIMAL(10,2) NOT NULL,
 CONSTRAINT fk_item_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
 CONSTRAINT fk_item_product FOREIGN KEY (product_id) REFERENCES products(id)
);
CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product ON order_items(product_id);
CREATE TABLE IF NOT EXISTS cart_items (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL,
 product_id BIGINT NOT NULL,
 quantity INT NOT NULL CHECK (quantity > 0),
 CONSTRAINT uq_cart UNIQUE(user_id, product_id),
 CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
 CONSTRAINT fk_cart_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_cart_user ON cart_items(user_id);
CREATE TABLE IF NOT EXISTS reviews (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 product_id BIGINT NOT NULL,
 user_id BIGINT NOT NULL,
 rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
 comment VARCHAR(1000),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 CONSTRAINT uq_review UNIQUE(product_id, user_id),
 CONSTRAINT fk_review_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
 CONSTRAINT fk_review_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_reviews_product ON reviews(product_id);

-- Safe, idempotent migration for databases created before the rental (thrift-store rent/buy) feature existed.
-- (No CHECK clause here: it is validated in AppServlet before every insert/update, and adding a CHECK to an
--  already-populated column via ALTER is more failure-prone across H2 versions than validating in code.)
ALTER TABLE products ADD COLUMN IF NOT EXISTS listing_type VARCHAR(10) NOT NULL DEFAULT 'SALE';
CREATE INDEX IF NOT EXISTS idx_products_type ON products(listing_type);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_name VARCHAR(120) NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_address VARCHAR(500) NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_phone VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method VARCHAR(10) NOT NULL DEFAULT 'COD';
