package com.tharunika.tharunikamart;
import com.tharunika.tharunikamart.dao.UserDAO; import com.tharunika.tharunikamart.model.User; import com.tharunika.tharunikamart.service.AuthService;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.*;
import java.sql.*;
import static org.junit.jupiter.api.Assertions.*;

/** Exercises the full register -> login path against an in-memory H2 database, including the email case-insensitivity fix. */
class AuthServiceTest {
 private static JdbcDataSource ds;
 private AuthService auth;

 @BeforeAll static void setUpDatabase() throws Exception {
  ds=new JdbcDataSource(); ds.setURL("jdbc:h2:mem:tharunikamart_auth_test;DB_CLOSE_DELAY=-1");
  try(Connection c=ds.getConnection();Statement st=c.createStatement()){
   st.execute("CREATE TABLE users(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name VARCHAR(120),email VARCHAR(180) UNIQUE,password_hash VARCHAR(100),role VARCHAR(20),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
  }
 }

 @BeforeEach void freshAuth(){ auth=new AuthService(new UserDAO(ds)); }

 @Test void registersThenLogsInWithMatchingRole() throws Exception {
  auth.register("Asha Rao","asha@example.com","password1","BUYER");
  User u=auth.login("asha@example.com","password1","BUYER");
  assertNotNull(u); assertEquals("Asha Rao",u.name());
 }

 @Test void loginIsCaseInsensitiveOnEmail() throws Exception {
  auth.register("Kiran","Kiran@Example.com","password1","SELLER");
  assertNotNull(auth.login("kiran@example.com","password1","SELLER"),"lowercase login should match the mixed-case registered email");
  assertNotNull(auth.login("KIRAN@EXAMPLE.COM","password1","SELLER"),"uppercase login should also match");
 }

 @Test void duplicateRegistrationIsRejectedRegardlessOfCase() throws Exception {
  auth.register("First","dup@example.com","password1","BUYER");
  assertThrows(IllegalArgumentException.class,()->auth.register("Second","DUP@EXAMPLE.COM","password1","BUYER"));
 }

 @Test void loginFailsOnWrongPasswordOrWrongRole() throws Exception {
  auth.register("Meera","meera@example.com","password1","BUYER");
  assertNull(auth.login("meera@example.com","wrongpass","BUYER"));
  assertNull(auth.login("meera@example.com","password1","SELLER"),"registered as BUYER, so logging in as SELLER must fail");
 }

 @Test void registerRejectsShortPasswordAndInvalidEmail() {
  assertThrows(IllegalArgumentException.class,()->auth.register("Name","not-an-email","password1","BUYER"));
  assertThrows(IllegalArgumentException.class,()->auth.register("Name","ok@example.com","short","BUYER"));
 }
}
