package com.tharunika.tharunikamart;
import com.tharunika.tharunikamart.dao.*; import com.tharunika.tharunikamart.model.Product;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.*;
import java.math.BigDecimal; import java.sql.*; import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

/** Exercises ProductDAO (including SALE/RENT listing types) and ReviewDAO against a throwaway in-memory H2 database. */
class ProductAndReviewDAOTest {
 private static JdbcDataSource ds; private static long sellerId,buyerId;
 private ProductDAO products; private ReviewDAO reviews;

 @BeforeAll static void setUpDatabase() throws Exception {
  ds=new JdbcDataSource(); ds.setURL("jdbc:h2:mem:tharunikamart_test;DB_CLOSE_DELAY=-1");
  try(Connection c=ds.getConnection();Statement st=c.createStatement()){
   st.execute("CREATE TABLE users(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name VARCHAR(120),email VARCHAR(180) UNIQUE,password_hash VARCHAR(100),role VARCHAR(20),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
   st.execute("CREATE TABLE products(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,seller_id BIGINT,name VARCHAR(180),description VARCHAR(2000),price DECIMAL(10,2),stock_qty INT,category VARCHAR(80),image_url VARCHAR(1000),listing_type VARCHAR(10) DEFAULT 'SALE',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
   st.execute("CREATE TABLE reviews(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,product_id BIGINT,user_id BIGINT,rating INT,comment VARCHAR(1000),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(product_id,user_id))");
  }
  try(Connection c=ds.getConnection()){
   try(PreparedStatement p=c.prepareStatement("INSERT INTO users(name,email,password_hash,role) VALUES('Seller','seller@test.local','x','SELLER')",Statement.RETURN_GENERATED_KEYS)){p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){r.next();sellerId=r.getLong(1);}}
   try(PreparedStatement p=c.prepareStatement("INSERT INTO users(name,email,password_hash,role) VALUES('Buyer','buyer@test.local','x','BUYER')",Statement.RETURN_GENERATED_KEYS)){p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){r.next();buyerId=r.getLong(1);}}
  }
 }

 @BeforeEach void freshDaos(){ products=new ProductDAO(ds); reviews=new ReviewDAO(ds); }

 @Test void createsAndFindsASaleListing() throws Exception {
  long id=products.create(sellerId,"Desk Lamp","Warm LED lamp",new BigDecimal("499.00"),5,"Home","",  "SALE");
  Product p=products.find(id).orElseThrow();
  assertEquals("Desk Lamp",p.name()); assertFalse(p.isRental()); assertEquals(5,p.stockQty());
 }

 @Test void createsARentalListingAndFiltersByType() throws Exception {
  products.create(sellerId,"Tent","4-person camping tent",new BigDecimal("150.00"),2,"Outdoors","","RENT");
  List<Product> rentals=products.search("","","RENT");
  assertTrue(rentals.stream().anyMatch(p->p.name().equals("Tent") && p.isRental()));
  List<Product> sales=products.search("","","SALE");
  assertTrue(sales.stream().noneMatch(p->p.name().equals("Tent")));
 }

 @Test void searchMatchesNameCaseInsensitively() throws Exception {
  products.create(sellerId,"Bluetooth Speaker","Portable speaker",new BigDecimal("899.00"),3,"Electronics","","SALE");
  List<Product> found=products.search("bluetooth","","");
  assertTrue(found.stream().anyMatch(p->p.name().equals("Bluetooth Speaker")));
 }

 @Test void reviewUpsertReplacesThePreviousRatingInsteadOfDuplicating() throws Exception {
  long id=products.create(sellerId,"Backpack","Sturdy travel backpack",new BigDecimal("999.00"),4,"Lifestyle","","SALE");
  reviews.upsert(id,buyerId,4,"Pretty good");
  reviews.upsert(id,buyerId,5,"Actually great");
  List<com.tharunika.tharunikamart.model.Review> forProduct=reviews.forProduct(id);
  assertEquals(1,forProduct.size(),"same buyer re-rating the same product should update, not duplicate");
  assertEquals(5,forProduct.get(0).rating());
  Map<Long,double[]> summary=reviews.summaryByProduct();
  assertEquals(5.0,summary.get(id)[0]);
  assertEquals(1.0,summary.get(id)[1]);
 }
}
